# Generated by Django 4.0.5 on 2022-06-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Capitulos', models.IntegerField()),
                ('Genero', models.CharField(max_length=100)),
                ('Status', models.CharField(choices=[('L', 'Lançamento'), ('F', 'Finalizado'), ('I', 'Indefinido')], max_length=1)),
            ],
        ),
    ]
